server:
  port: 4000
nats:
  url: nats://localhost:4222
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  docker:
    compose:
      lifecycle-management: start_and_stop
      enabled: true

#documentation
springdoc:
  api:
    docs:
      enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
  